# Generated by Django 4.2 on 2023-11-08 11:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("first_app", "0002_userprofileinfoform"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserProfileInfoForm",
            new_name="UserProfileInfo",
        ),
    ]
